name: Deploy ReactJS to GitHub Pages

on:
  push:
    branches: ["main"] # Thay "main" bằng nhánh chính của bạn nếu cần
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest" # Sử dụng phiên bản Node.js mới nhất
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Check build output
        run: |
          if [ -z "$(ls -A build)" ]; then
            echo "Error: build directory is empty!"
            exit 1
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./build" # Thư mục build của ReactJS

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
